---
- name: Gather Info for NFS Exports
  ansible.builtin.import_tasks:
    file: "gather-info.yaml"

- name: Create Datasets and Exports for Declared Configs
  ansible.builtin.import_tasks:
    file: "create-exports.yaml"

- name: Reconcile existing exports against desired
  ansible.builtin.import_tasks:
    file: "cleanup-exports.yaml"
    
# TODO: maybe put in different role, but deploy the NFS CSI Driver, delegating to localhost, with these parameters.

