---
- name: Gather Info for NFS Exports
  ansible.builtin.import_tasks:
    file: "gather-info.yaml"

- name: Create Datasets and Exports for Declared Configs
  ansible.builtin.import_tasks:
    file: "create-exports.yaml"

# TODO: perform existence check against existing against desired where if existing export file is not a key in desired export state should be absent
# TODO: when force_destroy is true delete the ZFS dataset as well
# TODO: maybe put in different role, but deploy the NFS CSI Driver, delegating to localhost, with these parameters.
