---
smallstep_ca_secrets_dir: ""
smallstep_ca_intermediate_ca_cert: |
  -----BEGIN CERTIFICATE-----
  MIIBxjCCAUygAwIBAgIQJOCYk8DimRuxLbNUHuZILzAKBggqhkjOPQQDAzAfMR0w
  GwYDVQQDExRkb254aW5rZXNoaXAgUm9vdCBDQTAeFw0yNTEyMjkwMTE2MTBaFw0z
  NTEyMjcwMTE2MTBaMCMxITAfBgNVBAMTGGRvbnR4aW5rZXNoaXAgSXNzdWluZyBD
  QTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABPYfVhZjQ+8om8/7CIiJzii8B8Rq
  DCg2571Oisug0FZ+DkjndZmOMPuXaGlsRT61ekZPYRaWEtuNcViiRnK6WiCjZjBk
  MA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQWBBSx
  MDjXPBJPCmBFZgEOd3pAb/8uyjAfBgNVHSMEGDAWgBTLbWsAMIcTcUzSTXivR9DD
  GoU4jjAKBggqhkjOPQQDAwNoADBlAjATL3AnH6E6YrhZzPgxkdxduiCIPEIDdp1u
  icHmqAd16Nk1B2cTuqBacdx6FzMfMEECMQCHC8L054CY7hQiVIix8ehS7TzfMT0O
  sgd7YIrMypOGZpw9jKHx5Tqd4IgZTi2Y1Vk=
  -----END CERTIFICATE-----

smallstep_ca_intermediate_ca_key: !vault |
  $ANSIBLE_VAULT;1.2;AES256;okd-homelab
  31346338646236356639636331363261646366656234656637353339366537343038393265353636
  3063363538386166616437643263376538373461663939310a383964613032373833303262626137
  38323838393436396465306438656534306266653664336333623139393661353233636231623433
  3730613830386333310a356136383637656262663539663665346563653037363233346437333664
  39336132353838643035396531386633306435386165356566646464616663333939666537336432
  63383135376434633131336533613865396133343030333939346263386565323461393730653564
  32663430663365306330646337383666366439373965336265316363616336323836653064366634
  34343037383930653938383636316433633561633637633930366638383634353439356439306332
  38313235643239643330343362336433346637623630383764646638393537373464363338393330
  34626537623234326435636466373362663132326366333465363035656365383339396539313232
  39613037353063613532643639313136316262346138306338343430616332623334353835353039
  34656534306535343365363564666563303939323336376539653730323230636332366561356161
  31623361356262313334613264643564623037316465363266303837633131626332343031636461
  30646633363963653362646264356436336262643061366161306132336661343463663231323530
  36656636343439333039623335333731613263613962363134376231333133393939303166646162
  33633661363461323135636461636564383064343064346537313235663430323133643234666133
  30373238393730613462346465616431613533326164343164333861633433313761313135386138
  66333839373134373032643932333864646536336532393966633832616362616234383332633462
  62306265376664656565666234313266383435613962623936636663303731343937613664343865
  36313663303265306262

smallstep_ca_intermediate_ca_password: !vault |
  $ANSIBLE_VAULT;1.2;AES256;okd-homelab
  62643861356436323230613638393334363631306538386431333536353164373965393036313232
  6335376136336439623762656263303361623836303365660a316538303038376436636266346661
  37303061636134366330336633393466313563393463623736623132306231363636633437656637
  3434383461316331620a366337626463366435636362646233393066623234333836323039653831
  36313036373935303332613732626361303063343335323935623033636236613964633961633332
  6566656439323938626464393963633162626438636364323633

smallstep_ca_root_ca_cert: |
  -----BEGIN CERTIFICATE-----
  MIIBvjCCAUSgAwIBAgIQHVfwnY6zztNJVwGLMDwupTAKBggqhkjOPQQDAzAfMR0w
  GwYDVQQDExRkb254aW5rZXNoaXAgUm9vdCBDQTAeFw0yNTA0MTMyMTAyMTVaFw0z
  NTA0MTEyMTAyMTVaMB8xHTAbBgNVBAMTFGRvbnhpbmtlc2hpcCBSb290IENBMHYw
  EAYHKoZIzj0CAQYFK4EEACIDYgAE1bc46hA5mLVojdjPTLVRLJMqkkg7hgGb+489
  39vS29akGcnuW8mQ4wFNr4i4sYUSNlZTwqWEI6RcIeUPfvBmhmQ22bfAmVliNDSF
  SGHUYV0q3kZp+66AO1XKplb4HSqSo0UwQzAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0T
  AQH/BAgwBgEB/wIBATAdBgNVHQ4EFgQUy21rADCHE3FM0k14r0fQwxqFOI4wCgYI
  KoZIzj0EAwMDaAAwZQIxANpinpQl73TRy+QhuFn/cS2u8vI/e0gnv8FYZfL0j8MZ
  MN+zonmtR1RcJSU7NwvpIAIwW+FjxPfKC+a7UJASPKAhfR7e50e+YISfKCG1k7w+
  tBQ4POeDPjCi2eQyt9CRDfCx
  -----END CERTIFICATE-----

smallstep_ca_provisioner_password: !vault |
  $ANSIBLE_VAULT;1.2;AES256;okd-homelab
  35666365626366633937366161363961613932643734386138333239373633656538616535396330
  3466613238666365356563383439353039363832393738320a343132396232343831326361316439
  61633734636432386264316439323630326366396539363636363965666631313038323132383363
  6436646161313534350a623266383539353663653361373139373630656331353139643264376165
  66306136346662303837643163626262633562643738303465626163356366643534376237363538
  31616333366638353537366432363261346430383465363433613437323734393431326161313035
  34666630373463653837643637343965393732666133303662386135326363316366333833633734
  63366239613961336235

smallstep_ca_cn: step-ca.apps.lab-01.okd.home.arpa
smallstep_ca_additional_sans:
  - step-ca.home.arpa

smallstep_ca_service_account_name: step-ca
smallstep_ca_namespace_name: smallstep-ca
