---
smallstep_ca_inter
# Replace after testing
smallstep_ca_root_ca_cert: |
  -----BEGIN CERTIFICATE-----
  MIIBxTCCAWqgAwIBAgIRAI647KbZgbXS87GtIGHEmcYwCgYIKoZIzj0EAwIwQDEa
  MBgGA1UEChMRUmVmZXJlbmNlIEluaXQgQ0ExIjAgBgNVBAMTGVJlZmVyZW5jZSBJ
  bml0IENBIFJvb3QgQ0EwHhcNMjUxMjI2MDQxODE3WhcNMzUxMjI0MDQxODE3WjBA
  MRowGAYDVQQKExFSZWZlcmVuY2UgSW5pdCBDQTEiMCAGA1UEAxMZUmVmZXJlbmNl
  IEluaXQgQ0EgUm9vdCBDQTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABPJgTx6v
  eqpl9xib4DdtjO6g6Dvb5LjJDMz4ohDHYx99sfn0LBI1qzEpC6jSlvDMfAZelh0o
  mL48cXfmgaCiD2ijRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/
  AgEBMB0GA1UdDgQWBBSizzzLgJGZJ0IGz1sxs6qiihTj2zAKBggqhkjOPQQDAgNJ
  ADBGAiEApwd/nMckYzUk1wjRnm87KYLJcdp3VnGM2Y0+6AWpotoCIQCO6LTbortJ
  D/qd1D9AgO4JomMbbl2SnV8UD/BEQhhcxQ==
  -----END CERTIFICATE-----
