---
smallstep_ca_intermediate_ca_cert: ""
smallstep_ca_intermediate_ca_key: ""
smallstep_ca_intermediate_ca_password: !vault |
  $ANSIBLE_VAULT;1.2;AES256;okd-homelab
  66316530363834336361616339383763323335343365663564353333613333383138353635326661
  6564643038336230613637333662613538663231303438380a353239346661613936653037303764
  62303037633732366365643231316330353062333165636366353238333332356562633261306465
  3562346133623036320a353030306262633035656631666261323730376436393463306465313531
  37333236663535326233646637633338633064346330626665646230346161333434306165633832
  61333030666333346434333763373536363064616434333762346564623230356365653135343736
  37393539323366643263613631646437373765646362316664383436656630326639373034613963
  64343135383364373236
# Replace after testing
smallstep_ca_root_ca_cert: |
  -----BEGIN CERTIFICATE-----
  MIIBxTCCAWqgAwIBAgIRAI647KbZgbXS87GtIGHEmcYwCgYIKoZIzj0EAwIwQDEa
  MBgGA1UEChMRUmVmZXJlbmNlIEluaXQgQ0ExIjAgBgNVBAMTGVJlZmVyZW5jZSBJ
  bml0IENBIFJvb3QgQ0EwHhcNMjUxMjI2MDQxODE3WhcNMzUxMjI0MDQxODE3WjBA
  MRowGAYDVQQKExFSZWZlcmVuY2UgSW5pdCBDQTEiMCAGA1UEAxMZUmVmZXJlbmNl
  IEluaXQgQ0EgUm9vdCBDQTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABPJgTx6v
  eqpl9xib4DdtjO6g6Dvb5LjJDMz4ohDHYx99sfn0LBI1qzEpC6jSlvDMfAZelh0o
  mL48cXfmgaCiD2ijRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/
  AgEBMB0GA1UdDgQWBBSizzzLgJGZJ0IGz1sxs6qiihTj2zAKBggqhkjOPQQDAgNJ
  ADBGAiEApwd/nMckYzUk1wjRnm87KYLJcdp3VnGM2Y0+6AWpotoCIQCO6LTbortJ
  D/qd1D9AgO4JomMbbl2SnV8UD/BEQhhcxQ==
  -----END CERTIFICATE-----
smallstep_ca_cn: step-ca.apps.lab-01.okd.home.arpa
smallstep_ca_additional_sans:
  - step-ca.home.arpa
