[tools]
just = "latest"
opentofu = "latest"
"ansible-core" = { version = "latest", uvx = "true", uvx_args = "--with ansible,kubernetes,openshift" }
"pipx:ansible-lint" = { version = "latest", uvx = "true", uvx_args = "--with ansible" }
