apiVersion: apps/v1
kind: Deployment
metadata:
  name: zot-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zot-registry
  template:
    metadata:
      labels:
        app: zot-registry
    spec:
      securityContext:
        sysctls:
          - name: net.ipv4.ip_unprivileged_port_start
            value: "0"
      containers:
        - name: zot
          securityContext: {}
          image: "ghcr.io/project-zot/zot-linux-amd64:v2.1.13"
          imagePullPolicy: IfNotPresent
          env: []
          ports:
            - name: zot
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: "/var/lib/registry"
              name: zot-registry-volume
            - mountPath: "/etc/zot"
              name: zot-registry-config
            - mountPath: "/etc/ssl/certs/zot"
              name: zot-registry-tls-cert
            - mountPath: /etc/ssl/private/zot
              name: zot-registry-tls-key
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: zot-registry-volume
          persistentVolumeClaim:
            claimName: zot-registry-volume
        - name: zot-registry-config
          configMap:
            name: zot-registry-config
        - name: zot-registry-tls-cert
          secret:
            secretName: zot-registry-certs
            items:
              - key: tls.crt
                path: zot-registry.crt
        - name: zot-registry-tls-key
          secret:
            secretName: zot-registry-certs
            items:
              - key: tls.key
                path: zot-registry.key

      dnsPolicy: ClusterFirst
