apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: "ghcr.io/project-zot/zot-linux-arm64:latest"
    newName: ghcr.io/project-zot/zot-linux-amd64
    newTag: v2.1.10

resources:
  - deployment.yaml
  - persistent-volume.yaml

secretGenerator:
  - name: zot-registry-certs
    type: "kubernetes.io/tls"
    files:
      - tls.crt=secrets/zot-registry.crt
      - tls.key=secrets/zot-registry.key

configMapGenerator:
  - name: zot-registry-config
    files:
      - config.json
